version: '3'

services:
  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: magento-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: supersecretpassword
      MARIADB_USER: magento
      MARIADB_PASSWORD: secretpassword
      MARIADB_DATABASE: magento
      
  # Elastic Search required by Magento 2.4
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: magento-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    restart: always
    container_name: magento-nginx
    ports:
      - "8080:80"
    volumes:
      - ./magento:/workspaces/magento
    depends_on:
      - mariadb
      - php

  php:
    container_name: magento-php
    build:
      context: ./php
      dockerfile: php.dockerfile
    restart: always
    volumes:
      - ./magento:/workspaces/magento

volumes:
  magento-mariadb-data:
