version: '3'

services:
  mariadb:
    image: mariadb:10.4
    container_name: magento-mariadb
    networks:
      - magento-network
    ports:
      - "3307:3307"
    volumes:
      - magento-mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_USER: magento
      MYSQL_PASSWORD: secretpassword
      MYSQL_DATABASE: magento


  # Elastic Search required by Magento 2.4
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: magento-elasticsearch
    networks:
      - magento-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    container_name: magento-nginx
    networks:
      - magento-network
    ports:
      - "8080:80"
    volumes:
      - ./magento:/workspaces/magento
    depends_on:
      - mariadb
      - php

  php:
    container_name: magento-php
    build:
      context: .
      dockerfile: php.dockerfile
    restart: always
    volumes:
      - ./magento:/workspaces/magento

volumes:
  magento-mariadb-data:

networks:
  magento-network:
      
